ConduitIO/mx-ui-components

addon/components/mxa/select.hbs
addon/components/mxa/select.js
addon/components/mxa/select/option.hbs
addon/modifiers/on-click-outside.js

+ Let our Select component accept HTML blocks
+ Refactor how on click outside works. This still isnt perfect interaction wise, but is better than what currently exists. This will require some more polish
Eventually we should refactor this to named components after we upgrade our ember versions across the UIs and this addon. This will allows us to really customize what we can do with the Select component, and add custom HTML content essentially anywhere.

Tweak Select component to allow blocks

---

.github/workflows/sync.yml

This should allow an automatic sync of the main branch anytime the source repository's main branch is updated.
See https://github.com/ConduitIO/mx-ui-components/runs/2271856211
Github Repo Sync: https://github.com/marketplace/actions/github-repo-sync
Github Actions Quickstart: https://docs.github.com/en/actions/quickstart

ops(github): sync main branch with changes on source repo

---

addon/components/mox/icon.js
addon/components/mox/list.hbs
addon/components/mox/list.js
addon/components/mox/list/header.hbs
addon/components/mox/list/item.hbs
stories/mox-icon.stories.js
stories/mox-list.stories.js
tests/dummy/public/svg-defs.svg
tests/integration/components/mox/icon-test.js
tests/integration/components/mox/list-test.js
tests/integration/components/mox/list/item-test.js

Part of https://github.com/meroxa/product/issues/515
This adds controls to the `Mox::List` component's header columns that would allow users to sort table entries alphanumerically.
Additionally, this PR includes new size variations of the `Mox::Icon` component.

feat(mox/list): add sorting functionality to table elements

---

addon/components/mxa/modal-dialog.hbs
package.json
yarn.lock

+ Rollback ember-keyboard to an earlier version that supports ember 3 -- See https://github.com/adopted-ember-addons/ember-keyboard#compatibility
+ Fixes modal title overflow in mxa components for Conduit

Fix modal title overflow + ember-keyboard dep

---

.changeset/wicked-jars-talk.md
addon/components/mox/list.js
tests/integration/components/mox/list-test.js

Part of https://github.com/meroxa/product/issues/515
With this update, the `Mox::List` component may rerender whenever the value of its `@items` argument changes.

fix(mox/list): allow rerender of sorted items on arg updates

---

.changeset/swift-bottles-trade.md
.github/workflows/release.yml
README.md

Part of https://github.com/meroxa/platform-ui-v1/issues/342
Follow-up to https://github.com/ConduitIO/mx-ui-components/pull/25
The new version of storybook that has been upgraded via https://github.com/ConduitIO/mx-ui-components/pull/25 requires Node 16. With this upgrade of the Node engine's version in our Github workflows, we're unblocking the CI action for the automatic release process [which is currently failing during the dependency installation step](https://github.com/ConduitIO/mx-ui-components/actions/runs/3851262348/jobs/6572887144).
```bash
Run yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error @storybook/ember-cli-storybook@0.6.0: The engine "node" is incompatible with this module. Expected version ">= 16". …
```

fix(ci): upgrade to Node 16 to unblock release GH action

---

.changeset/cool-pillows-argue.md
addon/components/mox/accordion.hbs
tests/integration/components/mox/accordion-test.js

Adds small functionality to the accordion, that makes the header toggleable by default

feat: make accordion header toggle by default

---

.changeset/tiny-boxes-live.md
.github/dependabot.yml
.github/workflows/dependabot-automerge-js.yml

Part of https://github.com/meroxa/engineering/issues/51
With this change, dependency upgrades to the latest patch version of an npm package will be automatically approved and merged.
This is excluding the automation of `minor` version upgrades. This way, we still have enough time for additional, manual testing of updates of dependencies that may lead to UX-breaking changes.

ci(dependabot): allow automatic upgrade of deps (patch version)

---

package.json
yarn.lock

Closes https://github.com/ConduitIO/mx-ui-components/security/dependabot/88
> Impact
A specially crafted HTTP request can trigger an uncaught exception on the Engine.IO server, thus killing the Node.js process.
> `TypeError: Cannot read properties of undefined (reading 'handlesUpgrades')
at Server.onWebSocket (build/server.js:515:67)
This impacts all the users of the [engine.io](https://www.npmjs.com/package/engine.io) package, including those who uses depending packages like [socket.io](https://www.npmjs.com/package/socket.io).`
> Patches
A fix has been released today (2023/05/02): [6.4.2](https://github.com/socketio/engine.io/releases/tag/6.4.2)
> This bug was introduced in version 5.1.0 and included in version 4.1.0 of the socket.io parent package. Older versions are not impacted.

deps(engine): upgrade engine.io to latest sec. patched version

---

.changeset/mean-news-tease.md
addon/components/mox/card.hbs
addon/components/mox/card/main.hbs
addon/components/mox/card/main.js
app/components/mox/card.js
app/components/mox/card/main.js
stories/header.css
stories/mox-card.stories.js
tests/dummy/public/svg-defs.svg
tests/integration/components/mox/card-test.js
tests/integration/components/mox/card/main-test.js

Closes https://github.com/meroxa/platform-ui-v1/issues/920
WIth this change, we're adding a new `Mox::Card` component to the UI library which can be used in e.g. list views.

feat(mox): add mox::card component

---

.changeset/blue-waves-travel.md
package.json
tests/dummy/config/deprecation-workflow.js
yarn.lock

Part of https://github.com/meroxa/platform-ui-v1/issues/727
With this change, we're updating the addon's [deprecation workflow configuration](https://github.com/mixonic/ember-cli-deprecation-workflow) to account for [4.x warnings from ember, ember-data and ember-cli](https://deprecations.emberjs.com/) respectively.

config(depr.): update depr. workflow for 4.x warnings

---

package.json
yarn.lock

Closes https://github.com/ConduitIO/mx-ui-components/security/dependabot/90
With this change, we're pinning the resolved version for `socket.io-parser` to include the latest security patch for the following vulnerability:
> _Impact_
A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process.
> TypeError: Cannot convert object to primitive value
at Socket.emit (node:events:507:25)
at .../node_modules/socket.io/lib/socket.js:531:14

deps(socket): upgrade socket.io-parser to latest security patch version

---

.changeset/early-bulldogs-rhyme.md
addon/components/mox/link-button.hbs
addon/styles/mx-ui-components.css
addon/tailwind.config.js
app/components/mox/link-button.js
stories/mox-link-button-light.stories.js
stories/mox-link-button.stories.js
tests/integration/components/mox/link-button-test.js

Closes https://github.com/meroxa/platform-ui-v1/issues/988
With this change, we're adding a new `Mox::LinkButton` component to the component library. The component is both dark and light mode capable. This way, we can already integrate its dark mode variant into the dashboard today.
|--|--|
|![link-dark](https://github.com/ConduitIO/mx-ui-components/assets/8811742/cc8e5c43-e93a-4859-bfa4-ea0ba2edf558)|![link-light](https://github.com/ConduitIO/mx-ui-components/assets/8811742/1f14a660-2a96-4942-8dfd-82ad16c406aa)|

feat(mox/link-button): add new link-button component

---

.changeset/wet-moose-lick.md
addon/components/mox/article.hbs
addon/components/mox/article/header.hbs
addon/components/mox/card.hbs
addon/components/mox/card/aside.hbs
addon/components/mox/card/aside.js
addon/components/mox/card/main.hbs
app/components/mox/article.js
app/components/mox/article/header.js
app/components/mox/card/aside.js
stories/mox-article-light.stories.js
stories/mox-article.stories.js
stories/mox-card-light.stories.js
tests/integration/components/mox/article-test.js
tests/integration/components/mox/article/header-test.js
tests/integration/components/mox/card-test.js
tests/integration/components/mox/card/aside-test.js

Closes https://github.com/meroxa/platform-ui-v1/issues/989
With this change, we're updating the UI for `Mox::Card` as part of [the redesign](https://github.com/meroxa/product/issues/832) and [app settings work](https://github.com/meroxa/product/issues/875). This also adds the following new components to the library:
```html
<Mox::Article::Header>
<:title>
Grandia
</:title>
<:subtitle>
category: videogames
</:subtitle>
</Mox::Article::Header>
```
```html
<Mox::Article>
Baphomet's Curse
</Mox::Article>
```
|--|--|
|![Screenshot 2023-07-07 at 1 20 02 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/113fd97b-4673-44db-8201-d88201592e28)|![Screenshot 2023-07-07 at 1 20 17 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/d978ba38-397f-44 …

Update mox::card UI + add new mox::article component

---

.changeset/tame-hats-draw.md
addon/components/mox/form-error.hbs
addon/components/mox/input.hbs
addon/components/mox/label.hbs
addon/components/mox/link-button.hbs
addon/tailwind.config.js
stories/mox-input-light.stories.js
stories/mox-label-light.stories.js
tests/integration/components/mox/form-error-test.js
tests/integration/components/mox/input-test.js
tests/integration/components/mox/label-test.js
tests/integration/components/mox/select-test.js
tests/integration/components/mox/text-area-test.js
tests/integration/components/mox/typeahead-select-test.js

Closes https://github.com/meroxa/platform-ui-v1/issues/1002
Part of https://github.com/meroxa/platform-ui-v1/issues/992
With this change, we're adding a new light mode variant to the `Mox::Input` and `Mox::Label` components. We're also tweaking the UI for the `Mox::LinkButton` component to match the latest designs more accurately. Finally, we're updating any test scenarios for existing components that are reusing `Mox::Input` to specifically emulate the dark mode testing scenario when asserting for the component's style.
| dark | light |
|--|--|
|![dark-inputz](https://github.com/ConduitIO/mx-ui-components/assets/8811742/5bcdf312-6e0c-49a6-9194-5b59526e55d4)|![light-inputz](https://github.com/ConduitIO/mx-ui-components/assets/8811742/0753cf13-6a63-495e-b7c8-2724eb975964)|
| before | after …

Update Mox::Input Component UI and several light-mode UI tweaks

---

.changeset/tricky-days-prove.md
addon/components/mox/global-header.hbs
stories/mox-global-header.stories.js
tests/integration/components/mox/global-header-test.js

Shifts around our global header to support the new redesign
+ Remove help-menu since it is unused in platform dashboard (Using user-menu will suit our needs fine here)
+ Shifted env-switcher to right side of header
+ Added global-links block so we can add links in the header

feat: add links block to global header

---

addon/components/mox/link.hbs
addon/components/mox/tabs/item.hbs
addon/styles/mx-ui-components.css
stories/mox-link-light.stories.js
stories/mox-tabs-light.stories.js
tests/integration/components/mox/tabs-test.js
tests/integration/components/mox/tabs/item-test.js

Adds light mode tabs + light mode links with correct hover states
-------------------

feat: light mode mox:link + mox:tab-items

---

.changeset/wise-pears-work.md
addon/components/mox/input.hbs
addon/components/mox/link.hbs
tests/integration/components/mox/input-test.js
tests/integration/components/mox/link-test.js

Part of https://github.com/meroxa/platform-ui-v1/issues/1029
This reduces the brightness of some colors used within the `Mox::Input` component and `Mox::Link`  in order to improve the elements' contrast on light backgrounds. This way, we can write automated accessibility tests for the work of https://github.com/meroxa/auth0-templates/issues/210
| light mode |  dark mode |
|--|--|
|![input-light-mode](https://github.com/ConduitIO/mx-ui-components/assets/8811742/16435bb0-09fb-4112-8c87-d36b7ff4bb2e)|![input-dark-mode](https://github.com/ConduitIO/mx-ui-components/assets/8811742/328dd1f6-ae78-48c9-acda-7a2ad2da24b2)|
| light mode | dark mode |
|--|--|
|![Screenshot 2023-07-21 at 1 13 06 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/d517f630-2168-4c28-adbc-725001c5d863)|![Sc …

upd(mox:input): update light mode UI for input fields

---

.changeset/tame-crabs-cross.md
addon/components/mox/text-area.hbs
stories/mox-text-area-light.stories.js
tests/integration/components/mox/text-area-test.js

Part of https://github.com/meroxa/platform-ui-v1/issues/1029
This adds a new light-mode variant for the `<Mox::TextArea />`  component.
|--|--|
|![area-dark](https://github.com/ConduitIO/mx-ui-components/assets/8811742/734c20dc-0df6-49e3-b02a-916fd8f5cd03)|![area-light](https://github.com/ConduitIO/mx-ui-components/assets/8811742/8bee6c58-52c6-49ce-bf32-63d94e4950aa)|

upd(mox:text-area): add light mode for component

---

.changeset/slow-beds-return.md
addon/components/mox/upload.hbs
addon/components/mox/upload.js
stories/mox-upload-light.stories.js
tests/integration/components/mox/upload-test.js

Part of https://github.com/meroxa/platform-ui-v1/issues/1029
With this change, we're adding a light-mode variant to the following components:
- `Mox::Upload`
|--|--|
|![upload-dark](https://github.com/ConduitIO/mx-ui-components/assets/8811742/4d2d8b67-9b8f-4394-94da-a1ee51798e27)|![upload-light](https://github.com/ConduitIO/mx-ui-components/assets/8811742/7550efc8-90af-4c25-8f6a-0f62340055a9)|

upd(mox:upload): add light mode for mox:upload comp.

---

.changeset/great-comics-own.md
addon/components/mox/input.hbs
addon/components/mox/search-input.hbs
addon/components/mox/select.hbs
addon/components/mox/select.js
addon/components/mox/select/option.hbs
addon/components/mox/typeahead-select.hbs
addon/components/mxa/select/option/category.hbs
package.json
stories/mox-select-light.stories.js
stories/mox-typeahead-select-light.stories.js
tests/integration/components/mox/input-test.js
tests/integration/components/mox/select-test.js
tests/integration/components/mox/typeahead-select-test.js

Closes https://github.com/meroxa/platform-ui-v1/issues/1029
With this PR, we're adding a light mode variant for the following components:
- `Mox::Select`
- `Mox::SelectOption`
- `Mxa::SelectOption::Category` (used within `Mox::SelectOption` and `Mxa::SelectOption`)
- `Mox::TypeaheadSelect`
|--|--|
|![select-dark](https://github.com/ConduitIO/mx-ui-components/assets/8811742/124e2a40-71f4-4972-a4f2-9c5471f0692c)|![select-light](https://github.com/ConduitIO/mx-ui-components/assets/8811742/f0081280-7bc5-49ef-a581-a7712373a05b)|
|--|--|
|![typea-dark](https://github.com/ConduitIO/mx-ui-components/assets/8811742/ab56497b-1869-4cd9-b3fe-e933093a7504)|![typea-light](https://github.com/ConduitIO/mx-ui-components/assets/8811742/d9c40227-077c-424b …

feat(mox:select): add light mode to mox/select components

---

.changeset/kind-beans-refuse.md
addon/components/mox/input.hbs
addon/styles/mx-ui-components.css
stories/mox-input-light.stories.js
stories/mox-input.stories.js

Follow-up to https://github.com/meroxa/platform-ui-v1/issues/1029
This applies UI fixes to the `Mox::Input` and `Mox:ThemeSwitch` components.
| before | after |
|--|--|
|![Screenshot 2023-07-26 at 6 18 18 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/7fd3a7dc-6cde-4a5f-9540-da9f92a9902a)|![Screenshot 2023-07-26 at 6 11 01 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/41cbd05a-c0a1-4a6c-a9d6-e98c01f7b48e)|
| before | after |
|--|--|
|![Screenshot 2023-07-26 at 6 18 23 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/9de67d58-ff3c-470a-8af2-df9b835eb0b5)|![Screenshot 2023-07-26 at 6 10 47 PM](https://github.com/ConduitIO/mx-ui-components/assets/8811742/db417044-1ff1-46b7-abf8-e467bd50583e)|

fix(mox): fix layout + alignment of mox:input + mox:theme-switch comp

---

.changeset/wicked-vans-wonder.md
addon/components/mox/global-header.hbs

adds `...attributes` to the global header so we can pass down attributes

fix: add attributes to global header

---

.changeset/unlucky-hats-look.md
addon/components/mox/link-to.hbs
addon/components/mox/link.hbs
tests/dummy/app/controllers/application.js
tests/dummy/app/controllers/application/subroute.js
tests/dummy/app/router.js
tests/dummy/app/routes/application.js
tests/dummy/app/routes/application/subroute.js
tests/integration/components/mox/link-test.js

Closes https://github.com/meroxa/platform-ui-v1/issues/1053
With this change, the `Mox::Link` component may now redirect to routes with query parameters, e.g. `/my-route?filter=foo`

fix(mox:link): allow mox:link to accept query params

---

.changeset/flat-shirts-battle.md
addon/components/mox/article.hbs
addon/components/mox/card.hbs
addon/components/mox/input.hbs
addon/components/mox/link-button.hbs
addon/components/mox/modal.hbs
addon/components/mox/section.hbs
addon/components/mox/select.hbs
addon/components/mox/theme-switch.hbs
addon/components/mox/toggle.hbs
addon/components/mxa/select.hbs
addon/components/mxa/tags-input.hbs
addon/components/mxa/typeahead-select.hbs
addon/styles/mx-ui-components.css

+ Updates our mox components to consistent dark/light themes based on new designs
+ Removes custom css in favor of loaded tailwind classes

feat: dark/light consistency across mox components

---

.changeset/polite-pets-switch.md
addon/components/mox/list/header.hbs
addon/components/mox/list/item.hbs
addon/components/mox/list/row.hbs
tests/integration/components/mox/list-test.js
tests/integration/components/mox/list/header-test.js
tests/integration/components/mox/list/item-test.js
tests/integration/components/mox/list/row-test.js
tests/integration/components/mox/toggle-test.js

Brings us in line with new designs of dark/light mode tables....so we don't have to do any !important nonsense in the consuming apps...

fix: light mode theming for tables
